services:
  dovecot:
    image: dovecot/dovecot:2.3.21
    restart: always
    ports:
    #  - "0.0.0.0:110:110" # pop3
    #  - "0.0.0.0:143:143" # imap
      - "0.0.0.0:993:993" # imaps
      - "0.0.0.0:995:995" # pop3s
    volumes:
      - "./volumes/dovecot_config:/etc/dovecot"
      - "./volumes/dovecot_passdb:/passdb"
      - "./volumes/imap_certs:/imap_certs"
      - "./volumes/pop_certs:/pop_certs"
      - "./volumes/mail:/var/spool/mail"
      - "./volumes/postfix_spool:/var/spool/postfix"
      - "./volumes/dovecot_logs:/var/log/dovecot"
  postfix:
    image: aoirint/postfix:20230719.4
    restart: always
    ports:
      - "0.0.0.0:25:25" # smtp
      - "0.0.0.0:465:465" # smtps
      - "0.0.0.0:587:587" # submission
    volumes:
      - "./volumes/postfix_config:/postfix"
      - "./volumes/mx01_certs:/mx01_certs"
      - "./volumes/smtp_certs:/smtp_certs"
      - "./volumes/mail:/var/spool/mail"
      # - "./volumes/postfix_spool:/var/spool/postfix"
      - "./volumes/postfix_logs:/var/log/postfix"
    depends_on:
      - dovecot
